# Generated by Django 4.2.6 on 2023-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about_us', models.TextField()),
                ('adress', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
