# Generated by Django 4.2.6 on 2023-10-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='iban',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
