# Generated by Django 4.2.6 on 2023-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0004_contactinfo_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='main_advert/')),
                ('description', models.TextField()),
            ],
        ),
    ]
